# Generated by Django 5.0.2 on 2024-02-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_remove_article_comment_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
