# Generated by Django 5.0.2 on 2024-02-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0005_subtopic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubTopic',
        ),
    ]
