# Generated by Django 5.0.2 on 2024-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
