# Generated by Django 5.0.2 on 2024-02-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_subtopic_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
