# Generated by Django 5.0.2 on 2024-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_alter_subtopic_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='note_link',
            field=models.URLField(default='https://www.cisco.com'),
        ),
    ]
