# Generated by Django 5.0.2 on 2024-03-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_subtopic_note_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.URLField(default='https://www.cisco.com'),
        ),
    ]
