# Generated by Django 5.0.2 on 2024-03-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_article_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
    ]
