# Generated by Django 5.0.2 on 2024-03-09 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_remove_article_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
